### ISSUE TITLE
Rearrange code structure in models

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#116]
Community tips: http://rails-bestpractices.com/posts/2011/05/31/keep-code-struture-in-models-consistent

**Comment by markets** [comment]
What do you think about something like?

1. Modules (includes, extends)
2. Constants 
3. Associations
4. 3rd-party macros (like devise, acts_as_taggable, ...)
5. Validations
6. Callbacks
7. Scopes
8. Class methods
9. Instance methods

**Comment by rewritten** [comment]
Macros for me are often at the same level as module inclusion. Actually I would love to switch from macros (specific methods that are already included somewhere) to including modules generated on the fly (from a configurable factory, take Virtus as an example), it would be much more explicit. Now with Module#prepend it could be done:

    include ActsAsTaggable.behaviour(on: :steroids)

Also, scopes are part of class definition, where validation is part of behavior. So I'd push scopes on top.

**Comment by rewritten** [comment]
(Note to the example: it is still "include", but the inclusion callback would prepend something else. )

**Comment by rewritten** [comment]
Basically, macros are dangerous because the implicitly rely on the method to be loaded by some other configuration or whatnot. By encapsulating it in an explicit module inclusion, it's clear that we are adding behaviour on the class and where this behavior is located.

**Comment by markets** [comment]
@rewritten I'm agree, macros is kind of obfuscated behaviour injected from somewhere (but a common practice in the Ruby/Rails gems ecosystem). Another good example from [equalizer](https://github.com/dkubb/equalizer) gem:

    include Equalizer.new(:latitude, :longitude)  

Regarding scopes, ok, but sometimes scopes are written just as class methods ...

In summary, for a first iteration, we can go with:

1. Modules (includes, extends)
2. Constants 
3. Associations
4. 3rd-party macros (like devise, acts_as_taggable, ...) => we can move it to 1) after this first reorganization 
5. Scopes
6. Validations
7. Callbacks
8. Class methods
9. Instance methods

This is not perfect at all, but I think it's quite clear compared to the current code organization.

**Comment by rewritten** [comment]
I insist with macros before internal constants. The rest is :+1:  . As for scopes as class methods, of course they are, but there is a difference between "repository" class methods (which are more correctly separated in other frameworks, like in django where you have specific classes for repository) and behavior attached to the class object (like factories)

**Comment by markets** [comment]
@rewritten all right regarding order! I misunderstood your comments about macros, I thought you meant rewrite macros in module-inclusion style... :sweat_smile: 

So:

* Modules (includes, extends)
* 3rd-party macros
* Constants 
* Associations
* Scopes
* Validations
* Callbacks
* Class methods
* Instance methods

I'll send a PR with those changes.

**Comment by markets** [comment]
@rewritten Just another question, where we should put attributes (attr_write, attr_readonly...)? Since they are part of class definition, they should be at some of the top sections, before constants? after constants?
