### ISSUE TITLE
Bug statistics

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#125]
La estadística "Tipo de intercambio" da error
https://redbooth.com/a#!/projects/638099/tasks/16430572

**Comment by PatriRor** [comment]
PR https://github.com/coopdevs/timeoverflow/pull/127

**Comment by PatriRor** [comment]
Datos demográficos: Al mostrar las etiquetas de las edades.

PR https://github.com/coopdevs/timeoverflow/pull/128

**Comment by PatriRor** [comment]
Solved in https://github.com/coopdevs/timeoverflow/pull/127 and https://github.com/coopdevs/timeoverflow/pull/128
