### ISSUE TITLE
Move remove_orphaned_users out of Member

### ISSUE THREAD

**Issue by carlesjove** [coopdevs/timeoverflow#140]
Currently, the `Member` model handles this:

``` ruby
after_destroy :remove_orphaned_users

private
def remove_orphaned_users
  user.destroy if user && user.members.empty?
end
```

However, this:
1. Should not be a `Member` reponsability
2. Generates a lot of work overload to the database

Instead, it should be moved somewhere else. Maybe a method accessible via a `DELETE` request from the admin's panel?

Also, **this method is really telling us that there is a bug in the app**, since there shouldn't be an scenario with orphans users.

**Comment by rewritten** [comment]
This is a specific requirement, a user can be a member of many orgs, and the org can remove his membership. The user itself has been required to be deleted when its last membership is removed. It can be delegated to an async job though, as soon as I have merged the rails 4.2 branch we will have ActiveJob and DJ available.

**Comment by carlesjove** [comment]
Ok

**Comment by rewritten** [comment]
Now we have ActiveJob in master (I was waiting for user testing of the corresponding branch). If you want to go on with the feature you are very welcome. I'd change the title into: **Move "removed orphaned users" into a command that can be executed as an async job**

**Comment by rewritten** [comment]
Also there is no command implementation chosen yet. I'll open a new issue to discuss this.
