### ISSUE TITLE
Command pattern

### ISSUE THREAD

**Issue by rewritten** [coopdevs/timeoverflow#141]
We need a library or internal implementation for commands, that should be compatible with running them with ActiveJob. Maybe the same ActiveJob can do the task?

Suggestions are welcome.

Once defined, features should be moved into commands following a common namespacing etc. One first candidate is the weekly mailer.

cc: @markets @carlesjove 

Note: ActiveJob does not support date and time arguments to jobs. And mixing in `GlobalID::Identification` into objects is spotty at the moment.

**Comment by markets** [comment]
Algunos gems interesantes:

* https://github.com/cypriss/mutations
* https://github.com/adomokos/light-service

De todas maneras, igual podríamos empezar por algo sencillo con POROs bajo `app/services/{service}` (o agrupados por contexto `app/services/{scope}/{service}`) que responden a `.run` o `.call` o `.perform`?

**Comment by rewritten** [comment]
Nowadays things are getting really interesting on functional patterns.

Look at this, that enables piping data through chains of callable injected dependencies:

http://dry-rb.org/gems/dry-transaction/

**Comment by rewritten** [comment]
So if at any point we are to implement a command, please let it be just a single instance of something that has a `call` method. It may be a simple Proc, ar anything above that, just keep the proc interface.

**Comment by markets** [comment]
👍  @rewritten As I commented in the past, simple POROs under `app/services` or `app/commands`, responding to `#call` or `#run` or something like this... is enough IMO. If everybody is agree with this approach, we can close the issue.

**Comment by rewritten** [comment]
Call is preferred so they can be replaced by procs in mocks or in simple dependency injection.
