### ISSUE TITLE
Presenter pattern

### ISSUE THREAD

**Issue by rewritten** [coopdevs/timeoverflow#142]
Draper? I remember having read some very harsh critic about it but I don't see many shortcomings. cc: @carlesjove @markets

**Comment by carlesjove** [comment]
Excuse me, but I don't know what a presenter is :v: :sweat_smile:

**Comment by rewritten** [comment]
http://mikepackdev.com/blog_posts/31-exhibit-vs-presenter
http://nithinbekal.com/posts/rails-presenters/

Basically,
1. move methods out from models, when those methods are just used for views/mails, and
2. add "jump" methods that internally navigate inside other related objects

The 1. aids in SRP for models, at the cost of having another object that acts as a Facade, and the 2. aid in following the Law of Demeter, in that consumers of the presenter object do not need to know anything about the internal structure of what's consumed, but only the declared interface.

**Comment by rewritten** [comment]
Example:
```ruby
class User
  attr_accessor :email
  attr_accessor :full_name
  attr_accessor :address
end

class UserPresenter < SimpleDelegator
  def formatted_email
    if full_name.present?
      "#{full_name} <#{email}>"
    else
      user.email
    end
  end

  def city
    address.city
  end

  private def user
    __getobj__
  end
end
```

**Comment by rewritten** [comment]
Also see: http://commandercoriander.net/blog/2014/10/02/isolating-active-record/

**Comment by markets** [comment]
Draper está bastante bien y tiene bastantes funcionalidades útiles: auto-decorate associated models, decorate collections, uso de helpers, generadores... 

Pero también veo buena idea empezar con `SimpleDelegator` bajo `app/presenteres` o `app/decorators`, cuando realmente una clase tenga bastantes métodos exclusivos de vistas (o métodos complejos).

Draper igual es demasiado grande/complejo para las necesidades actuales? Lo digo pensando tb en la naturaleza de TO y contributors (distintos niveles, gente empezando con Rails...); ya que cada nivel de abstracción puede suponer aprender un nuevo DSL, y para alguien con poca experiencia en Rails igual es menos "cómodo"...

**Comment by rewritten** [comment]
Mucha verdad. Un SimpleDelegator es más fácil. Más explícito sin duda. Cierro.
