### ISSUE TITLE
Template engine: ERB vs Haml vs Slim?

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#177]
Actualmente se utilizan los 3 (Haml más que el resto), en mi opinión creo que estaría bien unificar. Personalmente me quedo con ERB: más verbose, pero funciona out-of-the-box, no añades hard dependencies, más fácil para integrar themes (normalmente son HTML plano) y más cómodo para diseñadores que puedan trabajar sobre los templates. También es, en general, más rápido, aunque no estoy seguro que esto tenga un gran impacto en el tiempo de renderizado final de aplicaciones sencillas-medias.

cc @coopdevs/timeoverflow-contributors

**Comment by rewritten** [comment]
Am mi, personalmente, me gusta mucho más slim (lo mismo que jade en nodejs) pero las razones que das son muy buenas. :+1:

**Comment by rewritten** [comment]
Definitivamente ERB con unos controllers que devuelvan datos significativos (para que todo lo que llegue a la vista sean datos y no se tengan que usar helpers) (o unos presenters bien hechos - view model) es la manera más sencilla y más clara. Los datos van en el view model y solamente el aspecto en el template.

**Comment by rewritten** [comment]
First part: #214
