### ISSUE TITLE
Guía de instalación

### ISSUE THREAD

**Issue by alvarosaco** [coopdevs/timeoverflow#19]
¿Existe alguna guía de instalación del proyecto?

**Comment by markets** [comment]
@coopdevs/timeoverflow-contributors Creo que ésta tb la podríamos cerrar. Tenemos las guías de instalación en la Wiki (que por cierto podríamos ordernar/limpiar un poco):

* https://github.com/coopdevs/timeoverflow/wiki/Getting-started
* https://github.com/coopdevs/timeoverflow/wiki/Using-Vagrant-as-your-TimeOverflow-Development-Environment
