### ISSUE TITLE
Next steps (by sseerrggii)

### ISSUE THREAD

**Issue by rewritten** [coopdevs/timeoverflow#20]
* Al pagar horas como admin/superadmin necesitamos el campo fecha del pago y si es con cheque o no.
* Para los admin, que al ver el perfil de un usuario puedan añadirle fácilmente ofertas existentes (por título).
* Que el listado de movimientos de un usuario se pueda paginar, ademas los admin que tengan la opción de borrar un movimiento (con un aviso de ¿¿¿estás seguro???)
* Que en una nueva oferta/demanda por defecto esté marcado joinable y permanent. (solved in ee8e366)
* Sistema de tags con autocompletar.
* Traducción de categorías
* Listado de usuarios de baja, que un admin los pueda restablecer
* Comprobar que N.Documento sea único en el Banco (además de obligatorio, por seguridad) (solved in 19f06ba)
* En el form de usuario, la fecha de alta, por defecto hoy (solved in d6fc64c), lo mismo para fecha de inicio de oferta y demanda
* El orden del listado de usuarios por código de usuario ascendente. (solved in 7de3751)
* Estadísticas / listados de: usuarios más inactivos (que hace más tiempo que no hacen ningún intercambio), usuarios con el saldo más positivo, usuarios con el saldo más negativo), usuarios que cumplen años esta semana (-7 +7 dias de hoy)

**Comment by markets** [comment]
@coopdevs/timeoverflow-contributors Creo que también la podemos cerrar. Los puntos pendientes creo estan ya trackeados en Redbooth.
