### ISSUE TITLE
Implement 404 page

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#265]
We need to customize the Rails' default 404 page. It's not very user friendly. Looks like the server is on :fire: .

Our proposal is something functional as the following but we're open to suggestions:

![photo5992211769084455444](https://user-images.githubusercontent.com/762088/31613748-4cc18e34-b284-11e7-835c-829aaa0f9025.jpg)

Note that the broken left-alignment is not intended.

**Comment by admir23** [comment]
Hi @sauloperez , may I work on this?

**Comment by sauloperez** [comment]
All yours @admir23!

**Comment by sseerrggii** [comment]
We can solve too 500 error?

**Comment by reneesandefur** [comment]
@sseerrggii how can I duplicate the 500 error?

**Comment by sauloperez** [comment]
This https://stackoverflow.com/questions/4156490/how-to-test-500-html-in-rails-development-env might do the trick but you can always change the code to make it break.
