### ISSUE TITLE
Add link to your profile for image edit

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#274]
When you see your own profile you can edit your data and in your image profile you have a link to https://www.gravatar.com/

We want (before big change in avatar system) to put a link below avatar image to https://www.gravatar.com/

**Now**
![2017-10-30-133303_1920x1080_scrot](https://user-images.githubusercontent.com/2297137/32171196-9bd0d6b2-bd77-11e7-86ff-4d650a753197.png)

**With the new link**
![2017-10-30-132822_1920x1080_scrot](https://user-images.githubusercontent.com/2297137/32171194-9bb248c8-bd77-11e7-878a-fff1abd705ab.png)

**Comment by juanjochi** [comment]
I tried the link that sends you to the page to download, to change the profile picture and it worked well, I do not get the text to change your image.
You could put a button to take a picture from the camera.

**Comment by sseerrggii** [comment]
Hi @juanjochi !! This is only a task to add the text link below your image, now the image is the link to gravatar

We want (before big change in avatar system) to put a link below avatar image to gravatar in the future we will add the function to upload image

**Comment by juanjochi** [comment]
You could put avatar in Spanish by putting the link https://es.gravatar.com

**Comment by juanjochi** [comment]
I see that in Gravatar you can access the camera and a photo in the file, what I think is the mobile application and the profile of people unaccustomed to the use of computers that use the program, which would be easy to do the photo from the mobile.
