### ISSUE TITLE
Remove scroll in Firefox and Chromium

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#277]
![2017-10-31-181449_1366x768_scrot](https://user-images.githubusercontent.com/748971/32238278-af550eba-be67-11e7-9e42-bae54e9df7ce.png)

No se que `min-height`.

**Comment by enricostano** [comment]
cc/ @mllocs

**Comment by mllocs** [comment]
@enricostano can you share your screen resolution please?

**Comment by enricostano** [comment]
@mllocs `1366 x 768`

**Comment by markets** [comment]
@enricostano @mllocs 👋 Maybe we can consider this as done by #375? I don't see those scroll bars in latest `firefox` resizing to `1366 x 768` and latest `develop`.

**Comment by sauloperez** [comment]
I would close this and reopen it if we need to. It's old and chances are that it was fixed by #375

**Comment by enricostano** [comment]
Yep, seems solved to me. Thanks!!!
