### ISSUE TITLE
Fix login box

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#278]
![2017-10-31-182416_1366x768_scrot](https://user-images.githubusercontent.com/748971/32238724-e837dca2-be68-11e7-8448-dc178ed3b1ec.png)

**Comment by enricostano** [comment]
cc/ @mllocs

**Comment by mllocs** [comment]
what about removing that "TimeOverflow" header text? You have that name right on the top bar, quite visible already.

**Comment by enricostano** [comment]
ask @sseerrggii 😬

**Comment by sauloperez** [comment]
Agree with @mllocs

**Comment by sseerrggii** [comment]
Agree with @mllocs :+1: also check sizes in mobile

In my mobile resolution the input boxes (mail/password) are too big

**Comment by mllocs** [comment]
👍 willdo

**Comment by Matt-Yorkley** [comment]
It will be different for every screen, no? I think the css positioning for the devise modal needs to be rethought, instead of just cutting off the header text.

![screenshot from 2018-01-08 00-19-12](https://user-images.githubusercontent.com/9029026/34655933-c8a00d0c-f409-11e7-80db-6112ec06cd70.png)

**Comment by sauloperez** [comment]
It's just that the modal should always fall below the nav bar, and without title, right?

**Comment by Matt-Yorkley** [comment]
Agreed. Currently it seems to move up or down depending on how large it is.

**Comment by sauloperez** [comment]
Now that we merged https://github.com/coopdevs/timeoverflow/pull/282 this seems like a good follow-up. Still interested @Matt-Yorkley ?

**Comment by juanjochi** [comment]
I do not know if it will work but I changed the container size of 500px and put it to 649px and it seems that the whole box looks good, I put the screens.
![captura de pantalla_2018-03-09_14-23-26](https://user-images.githubusercontent.com/37113489/37210696-ee1963c4-23a9-11e8-8593-2130c636cf7e.png)
![captura de pantalla_2018-03-09_14-23-57](https://user-images.githubusercontent.com/37113489/37210709-fba2c03a-23a9-11e8-9792-7a9d01bf74f1.png)
![captura de pantalla_2018-03-09_14-25-34](https://user-images.githubusercontent.com/37113489/37210899-8d01bd56-23aa-11e8-9956-5503ec085fb3.png)

**Comment by markets** [comment]
@enricostano @mllocs @sauloperez 👋 Maybe we can consider this as done by #375?

**Comment by Matt-Yorkley** [comment]
Looks like this issue can't be closed yet:
![screenshot from 2018-06-21 23-33-31](https://user-images.githubusercontent.com/9029026/41748911-bc093e96-75ab-11e8-923f-0f791552e70d.png)

**Comment by markets** [comment]
Right @Matt-Yorkley! Thanks for looking into this :+1:

**Comment by enricostano** [comment]
![2018-08-08-135859_1366x768_scrot](https://user-images.githubusercontent.com/748971/43835913-e1f04cc0-9b13-11e8-9183-a6ec1060ad43.png)

This is how I see it now. cc/ @mllocs @Matt-Yorkley @markets
