### ISSUE TITLE
Devise flash messages inside login box

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#279]
In  /users/sign_in we want the devise messages inside the login box

![screenshot-2017-11-2 https www timeoverflow org](https://user-images.githubusercontent.com/2297137/32317374-f3e141b4-bfb3-11e7-8737-29fda3b431ba.png)

like reset password page /users/password/new

![screenshot-2017-11-2 https www timeoverflow org 1](https://user-images.githubusercontent.com/2297137/32317571-7bf0da6a-bfb4-11e7-87f0-44464b4c0069.png)

**Comment by sauloperez** [comment]
Done in https://github.com/coopdevs/timeoverflow/pull/282
