### ISSUE TITLE
Enable test coverage

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#281]
We need test coverage to ensure there are no bits of untested code. Tests make our life easier now that we are trying to refactor things to improve the maintainability of the codebase and we'll work on new features soon.

We should configure code climate's test coverage by means of SimpleCov. See https://docs.codeclimate.com/v1.0/docs/configuring-test-coverage and https://docs.travis-ci.com/user/code-climate/.

**Comment by markets** [comment]
Added SimpleCov in :point_right: #459

**Comment by markets** [comment]
1st step, SimpleCov, added in :point_right: #459

**Comment by markets** [comment]
@sauloperez 2nd and final step (code climate in ci) implemented in #478 :fireworks:
