### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#289]
More and more security vulnerabilities are popping up notified by GitHub. It feels like in general, we're getting out of date on our dependencies. We should put our efforts on doing a major bum up so that it's easy and painless to apply single upgrades when needed.

This deserves some investigation so that we can come up with a strategy to do it as I assume most of the gems will need decent upgrades.

**Comment by markets** [comment]
@sauloperez During the last year we updated a lot of dependencies, maybe we should close this one and open individual issues for each gem that needs an important update?

**Comment by enricostano** [comment]
We'll also be able to update more gems once we get to a more recent Ruby version.
