### ISSUE TITLE
log Rails in production

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#309]
Production's log is totally empty, even when doing a `tail -f log/production.log` and executing the app.

```
timeoverflow@Ubuntu-1510-wily-64-minimal:~/current$ ll log/
total 12296
drwxrwxr-x 2 timeoverflow timeoverflow     4096 Mar  7  2016 ./
drwxrwxr-x 7 timeoverflow timeoverflow     4096 Mar  3  2016 ../
-rw-rw-r-- 1 timeoverflow timeoverflow 12575542 Jan 29 09:03 cron_log.log
-rw-rw-r-- 1 timeoverflow timeoverflow        0 Mar  3  2016 production.log
```

**Comment by markets** [comment]
Hi @sauloperez maybe this is fixed with the new infra?

**Comment by sauloperez** [comment]
Good catch @markets there are things we have to clean up first but most likely this got fixed with the migration, yes. Now it's logging in `log/next.log` due to https://github.com/coopdevs/timeoverflow/blob/develop/config/environments/next.rb but I bet it'll do the same when we use the production env.

**Comment by markets** [comment]
@sauloperez time to close?

**Comment by sauloperez** [comment]
Yep, thanks for the heads-up. This is now fixed. The problem I see now is that we don't have any sort of log rotation :sweat_smile:
