### ISSUE TITLE
Add not null and unique constraint in member_uid column

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#311]
So far the `member_uid` has a validation at model level that ensure both: its presence, and its uniqueness by organization. This however does not prevent violations. Since this is not ensured at DB level, race conditions can lead to duplicates.

We should add a unique index plus a not null constraint on that column.

**Comment by nflorentin** [comment]
Hi,

I can do it but I'm struggling with the schema file structure.sql. I tried with postgres 9.4 but my structure.sql always ends different than the one of the repo. I would prefer not to edit it by hand after running the migrations.

Can you confirm that you are using pg9.4 in development ?

Thanks! :-)

**Comment by sseerrggii** [comment]
I think so 9.4 https://github.com/coopdevs/timeoverflow-provisioning/blob/a60823842f684dccf6928795acf763735a9fd087/roles/database/tasks/main.yml#L10
