### ISSUE TITLE
Refactor memberships query in users controller

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#312]
Now that the user's query also fetches their membership and account, as shown below:

https://github.com/coopdevs/timeoverflow/blob/6660a79c261e93fd3d148b590d3d5f1223bda217/app/controllers/users_controller.rb#L8-L14

There's no point in fetching the memberships and building a Hash associating the user and his membership, as shown below:

https://github.com/coopdevs/timeoverflow/blob/6660a79c261e93fd3d148b590d3d5f1223bda217/app/controllers/users_controller.rb#L16-L20

We already have that information. We simply need to access it directly from each of the user records returned by the first query.

**Comment by markets** [comment]
@sauloperez I'm going to close this one, as it has been refactored ✅ in #351 (now it relies on the decorated member instead of user + membership).
