### ISSUE TITLE
Remove N+1 queries from users list view

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#313]
The portion of the `_users_row.html.erb` below:

https://github.com/coopdevs/timeoverflow/blob/6660a79c261e93fd3d148b590d3d5f1223bda217/app/views/users/_user_rows.html.erb#L27-L61

Introduces few N+1 queries that come from the various custom path helper used there.

**Comment by sseerrggii** [comment]
https://github.com/coopdevs/timeoverflow/blob/develop/app/views/users/_user_rows.html.erb

@sauloperez is this still valid?

**Comment by mllocs** [comment]
This looks like fixed 👍
