### ISSUE TITLE
Remove N+1 from shared/_post view

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/timeoverflow#318]
The line below is responsible for a N+1:

https://github.com/coopdevs/timeoverflow/blob/94a4ad8baa4e947f80d2cfef8c1bcf1ec287b95b/app/views/shared/_post.html.erb#L34

Due to:

https://github.com/coopdevs/timeoverflow/blob/94a4ad8baa4e947f80d2cfef8c1bcf1ec287b95b/app/models/post.rb#L122-L124

That method is going introduce N+1 every time is used, as it is very likely that is going to be used as part of a larger query.

We should rely on eager loading the `members` association when needed instead.

**Comment by gpks** [comment]
I would love to try to fix this :)

**Comment by sauloperez** [comment]
Hi @gpks ! please go ahead. Keep in mind that the app has changed considerably recently so make sure you check the N+1 still exists first. Sorry for any inconvenience.

**Comment by enricostano** [comment]
@sauloperez can we close this issue? It seems that the N+1 is not there anymore. Right?

**Comment by sauloperez** [comment]
It seems so. Let's close it
