### ISSUE TITLE
Delete a organization

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#359]
Superadmin can't delete a organization: If some admin ask to to remove all timebank activitity we delete all the members (and users if they haven't another membership) and after that we change the name of timebank with something like "to delete someday" 

We need a way to remove all Organitzation activity through active admin panel

**Comment by markets** [comment]
Work in progress 👉 #368

**Comment by markets** [comment]
Hi 👋 

I agree with @enricostano. I'd say no 🔥, even more taking @sseerrggii's comments:

> We need a way to remove all Organitzation activity through active admin panel

I'll wait for a consensus to be reached to finish with #368.

**Comment by sseerrggii** [comment]
Exactly, users with organization membership will loose this membership and can't accs to anything to this organization, we should delete everything related with this organization.

**Comment by sauloperez** [comment]
Just to be crystal clear, do we all agree on the impact removing all the data of an org. will have on the future feed of events? When checking the feed you won't suddenly see an event you just saw 2min ago.

**Comment by enricostano** [comment]
We also have a foreign key in `PushNotification#event_id`, that will :boom: if we try to delete an `Event`:
https://github.com/coopdevs/timeoverflow/blob/develop/db/schema.rb#L227

2 things on this:
 - let's remove `PushNotification` when we delete an `Event`
 - let's add the `ON DELETE CASCADE` in all the tables at SQL level where we add `dependent: :destroy` in the AR model

what do you think?

**Comment by sseerrggii** [comment]
@sauloperez that's correct, if you are removed from the membership of an organization, you will no longer have access to that organization's feed

**Comment by sauloperez** [comment]
My point was that other's that may belong to other organizations as well, will see the events related to the removed organization disappear from the feed.
