### ISSUE TITLE
Use RSpec scope and remove global namespace

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#362]
Discussed in https://github.com/coopdevs/timeoverflow/pull/361#issuecomment-390795850

Add `config.expose_dsl_globally = false` and use `RSpec.describe`, etc.

More info: https://relishapp.com/rspec/rspec-core/v/3-0/docs/configuration/global-namespace-dsl

**Comment by markets** [comment]
Fixed by :point_right: #413
