### ISSUE TITLE
Move whenever cron job to sidekiq-cron

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#373]
https://github.com/coopdevs/timeoverflow/blob/develop/Gemfile#L20
https://github.com/coopdevs/timeoverflow/blob/develop/config/schedule.rb

https://trello.com/c/vCkaG7TW/124-move-whenever-cron-job-to-sidekiq-cron

**Comment by markets** [comment]
@enricostano :point_right: #401
