### ISSUE TITLE
Switching between organizations doesn't work anymore

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#383]
I guess the regression was introduced by https://github.com/coopdevs/timeoverflow/commit/b9d9b9636c806d48aad7e75cd353160572750689#diff-33bef3083bae5b2e2bea316eab44c9fdL2

We basically excluded `set_current` action from the `before_filter` conditions.

**Comment by markets** [comment]
oh my! 😱 

you're totally right @enricostano :pray: adding `:set_current` into the `before_filter :load_resource` should fix this issue

**Comment by enricostano** [comment]
@markets don't worry :+1: Will do in #382
