### ISSUE TITLE
Show only >0 occurrences tags when you create Post

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#387]
When user creates new offer/demand (Post) can select tags, we show "autocomplete" with tags used in all history organization. 

But we want to show only tags presents in 1 or more **active** posts

**Comment by enricostano** [comment]
Why?

**Comment by sseerrggii** [comment]
Sorry, title shoud be >0

* We don't want to suggest tags that are not used in other posts
* Maybe user creates a post with orthographic errors in tag and later user or admin change it, the tag with errors should not be suggested in the future
