### ISSUE TITLE
Redirect after post show and login

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#391]
When you see a post and you are not logged in you see a button for login

After the login you should be redirected to this post show

![fireshot capture 90 - - https___staging timeoverflow org_offers_25](https://user-images.githubusercontent.com/2297137/42505739-f522df5a-843f-11e8-9d5a-973250160081.png)

http://community.coopdevs.org/t/redireccionar-al-entrar-por-post/29

**Comment by markets** [comment]
@enricostano I think this would be fixed by your changes in #249

**Comment by enricostano** [comment]
@markets could be :+1:

**Comment by sseerrggii** [comment]
I reopen because it was not fixed, it is a important improvement for the user experience
