### ISSUE TITLE
Copy for notificactions (email)

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#410]
In a user data we have two checks for notifications, one is for email notifications and other is for mobile push notifications
![fireshot capture 21 - banco de tiempo local - https___staging timeoverflow org_members_1_edit](https://user-images.githubusercontent.com/2297137/44395586-9e75b300-a53a-11e8-94eb-54f377e682f3.png)

The problem is first notifications check is described as generic "notifications", we should change it for  "e-mail notificatons"

Can I change directly the copys in yml files or is it needed tot change also the key names

![fireshot capture 20 - coopdevs_timeoverflow_ - https___www localeapp com_projects_10031_translations](https://user-images.githubusercontent.com/2297137/44395699-f7dde200-a53a-11e8-8798-93cbeeb960f4.png)

@enricostano @mllocs

**Comment by enricostano** [comment]
If we don't change the `notifications` column in the `users` table we should at least add a comment in the `User` model, but I don't see where. [Here](https://github.com/coopdevs/timeoverflow/blob/develop/app/models/user.rb#L33)? :thinking:

**Comment by sseerrggii** [comment]
I think we can close this issue, very low priority
