### ISSUE TITLE
Remove deprecated Timeoverflow related repos 

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#420]
Hi people! :wave: 

![captura de pantalla 2018-09-01 a la s 17 23 00](https://user-images.githubusercontent.com/576701/44947321-cd7a0780-ae0b-11e8-8a55-9d817ab35aa8.png)

Maybe we can delete those deprecated Timeoverflow related repos, what do you think? They are empty repos by the way, so it's safe to just :scissors: 

It would be clearer regarding which repos are actually maintained.

**Comment by sauloperez** [comment]
Done! thanks for the heads-up!
