### ISSUE TITLE
Members list, paginate in even numbers

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#422]
With the new view of members, we continue paging every 25 members, but in desktop we see two cols, so will be better to paginate every 20 members.

![fireshot capture 28 - banco de tiempo local - https___staging timeoverflow org_members](https://user-images.githubusercontent.com/2297137/45040336-0f9e8580-b066-11e8-8e37-4a8f7e509c08.png)

**Comment by markets** [comment]
@sseerrggii did you mean 20 on both sections `/members` and `/members/manage`? Or you prefer something like 20 on `/members` and 30 on `/members/manage`? I don't know... just asking, maybe under the `manage` section makes sense to display more records.

**Comment by sseerrggii** [comment]
Mmmm :thinking: 

I'm not find reasons for have more records on ```/members/manage``` , we can change both to 20.
