### ISSUE TITLE
Can't find create container script

### ISSUE THREAD

**Issue by BitsofSpace** [coopdevs/timeoverflow#423]
I'm following the [lxc documentation](https://github.com/coopdevs/timeoverflow/wiki/Build-development-environment-with-LXC-for-GNU-Linux) but when trying to run the create container script, it says it doesn't exist. I can't find this file. 

I appreciate help with this. 

Thanks in advance.

**Comment by danypr92** [comment]
Hi!
I'm sorry, but that documentation is obsolete, we need to update it.

Now we are using this [`devenv`](https://github.com/coopdevs/devenv) tool. This tool is basically the old script but we can use it in all own projects. 

You only need clone the `devenv` repo and `make` it.
All this info are in the [`devenv`](https://github.com/coopdevs/devenv) repository.

Thank you for showing us this documentation problem. :wink:

**Comment by BitsofSpace** [comment]
@danypr92 
Gracias por la actualización. Al correr 'sudo devenv' en el directorio de 'time-provisioning' me sale:

~/.bin/timeoverflow-provisioning$ sudo devenv
Creating config file: /tmp/ubuntu.timeoverflow.conf
* CONFIGURATION:
  - Name: timeoverflow
  - Distribution: ubuntu
  - Release: xenial
  - LXC Configuration: /tmp/ubuntu.timeoverflow.conf
  - Host: local.timeoverflow.org
  - Project Name: timeoverflow
  - Project Directory: /home/grieta/.bin/timeoverflow
  - Will mount on: /var/www/timeoverflow
  - User: timeoverflow
  - Group: timeoverflow

Creating container timeoverflow
**lxc-create: confile.c: parse_line: 2008 unknown key lxc.net.0.type
lxc-create: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.net.0.type = veth

lxc-create: confile.c: parse_line: 2008 unknown key lxc.net.0.type
lxc-create: parse.c: lxc_file_for_each_line: 57 Failed to parse config: lxc.net.0.type = veth

lxc-create: tools/lxc_create.c: main: 318 Error creating container timeoverflow**

**Comment by danypr92** [comment]
@BitsofSpace si nos puedes copiar el resultado de:
`cat /tmp/ubuntu.timeoverflow.conf`
nos ayudaría mucho para saber como resolver tu problema.

También si puedes indicar que versión de LXC estas utilizando:
`lxc-create --version`

En la versión 2.1 de LXC se cambió la configuración referente al network de `lxc.network.type` a `lxc.net.[i].type`. Al parecer el error es con la key `lxc.net.0.type`, por lo que si tienes una versión de LXC anterior a la 3.0.0 puede que este sea el fallo.

https://linuxcontainers.org/lxc/news/#network-configuration

Gracias!

**Comment by BitsofSpace** [comment]
@danypr92 
la versión de lxc que tengo es '2.0.7' y lo que escupe el cat de ese archivo es:
`# Network
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxcbr0

# Volumes
lxc.mount.entry = /home/grieta/.bin/timeoverflow /var/lib/lxc/timeoverflow/rootfs//var/www/timeoverflow none bind,create=dir 0.0
`

**Comment by danypr92** [comment]
@BitsofSpace disculpa por tardar en contestar.
Parece que tendrás que actualizar la versión de `lxc` que tienes instalada, pues como comento en el anterior comentario:

> En la versión 2.1 de LXC se cambió la configuración referente al network de lxc.network.type a lxc.net.[i].type. Al parecer el error es con la key lxc.net.0.type, por lo que si tienes una versión de LXC anterior a la 3.0.0 puede que este sea el fallo.
[linuxcontainers.org/lxc/news/#network-configuration](https://linuxcontainers.org/lxc/news/#network-configuration)

Un saludo!
