### ISSUE TITLE
Text overflow on members list

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#425]
![descarga](https://user-images.githubusercontent.com/2297137/45290439-e2335b00-b4ef-11e8-9e1a-3c9b1ebb0f1d.png)

**Comment by sseerrggii** [comment]
![fireshot capture 34 - banco de tiempo local - https___staging timeoverflow org_members](https://user-images.githubusercontent.com/2297137/45293746-558d9a80-b4f9-11e8-9d32-df9e3c70e993.png)
1 column works fine

**Comment by markets** [comment]
Fixed by #436
