### ISSUE TITLE
Tel number on admin user creation

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#426]
When I create a new user as superadmin, if I do not fill in the telephone field, it seems to be shown as tel:// although in the database the field is empty :thinking: 

Strange.... because if you create as admin this does not happen

![fireshot capture 39 - banco de tiempo a borrar - https___staging timeoverflow org_members](https://user-images.githubusercontent.com/2297137/45634660-4a131400-baa3-11e8-8812-ddc2b8d6e782.png)

**Comment by markets** [comment]
Fixed by #436
