### ISSUE TITLE
In /members/manage view don't redirect to /member after cancel membership 

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#431]
Now when you are in /members/manage the action of delete membership redirect to /members 
Will be more useful to keep admin user in the same view

![peek 20-09-2018 13-21](https://user-images.githubusercontent.com/2297137/45815192-2f75b080-bcd8-11e8-9fc2-a4399570d628.gif)

**Comment by markets** [comment]
@sseerrggii fix pushed in #416
