### ISSUE TITLE
Send email notifications in user language 

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#453]
Users receives email notifications always in ES

We want to send notifications in language chosen by user (LOCALE field in user table)

http://community.coopdevs.org/t/eleccion-de-idioma-en-el-boletin-de-avisos-semanal/730

**Comment by denysmedynskyi** [comment]
I can take it

**Comment by sseerrggii** [comment]
Hi @denysmedynskyi !!
Any news for this issue?

**Comment by markets** [comment]
@sseerrggii I'll take care of this one, but would be nice to implement this after #401, to avoid big diffs

**Comment by sseerrggii** [comment]
@markets 

![giphy](https://user-images.githubusercontent.com/2297137/54190714-aab06600-44b4-11e9-9377-4d46623fc45d.gif)
