### ISSUE TITLE
Sort members list by last_sign_in_at

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#468]
In this commit https://github.com/coopdevs/timeoverflow/pull/436/commits/b0d675ce92a5153085411382c372fe9794cb6a73#diff-4e05ad0d64e6100656b63ad1e78f32c5R6 @mllocs  try to sort members in `/members` by last_sign_in_at but seems that ransack have troubles to sort null results at the end. 

For that we revert the change https://github.com/coopdevs/timeoverflow/pull/436/commits/9208d17bf00ef39e5d8b9d7dace87ccbc795d6df

Can we fix it? Will be good to see different members in this main page `/members`

Also is better to have members sorted by *activity* (Sorted by date of last transfer of member)

**Comment by sseerrggii** [comment]
@markets can you help here?

Only this issue remains to be done on second quarter of 2019 :love_letter:

**Comment by markets** [comment]
@sseerrggii work started in :point_right: #495
