### ISSUE TITLE
Delete unused ( maybe? ) columns in posts table

### ISSUE THREAD

**Issue by Morantron** [coopdevs/timeoverflow#471]
I'm not 100% sure, but i think this columns here are unused? ( at least `permanent` and `joinable` )

https://github.com/coopdevs/timeoverflow/blob/857643cf6c36c7944cda5ee55101c89088a2dce4/db/schema.rb#L144-L146

**Comment by enricostano** [comment]
https://github.com/coopdevs/timeoverflow/commit/4f56c826489310cf7604de218c6fe8938c76f247#diff-df2014f8b8976aed72db66eccb63e298R4

**Comment by Morantron** [comment]
that commit is from 2013, no? have you `git pull`ed recently? :trollface:

**Comment by sseerrggii** [comment]
I am pretty sure we don't use this fields

**Comment by sseerrggii** [comment]
![giphy](https://user-images.githubusercontent.com/2297137/54832366-50858100-4cbc-11e9-8ee1-b61cc4a1200f.gif)

**Comment by markets** [comment]
Fixed by #492 :hocho: :hocho: :hocho:
