### ISSUE TITLE
Fix favicon issue in staging

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#480]
It seems an issue valid only for https://staging.timeoverflow.org

We have 2 calls to `favicon.ico`:

https://github.com/coopdevs/timeoverflow/blob/d0f2bbfb08f70bc1c8b7b8f32a721eca42045150/app/views/layouts/application.html.erb#L9

https://github.com/coopdevs/timeoverflow/blob/8614f55dac9e54e299fa7a53447a077b6deb54ea/app/views/layouts/report.html.erb#L12

but we don't have any favicon...

```console
I, [2019-03-15T17:16:08.806952 #17899]  INFO -- : Started GET "/favicon.ico" for 66.249.66.154 at 2019-03-15 17:16:08 +0000
F, [2019-03-15T17:16:08.812329 #17899] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
[...]
```

**Comment by enricostano** [comment]
@sseerrggii what should we do?

**Comment by markets** [comment]
@enricostano https://www.timeoverflow.org/favicon.ico it works for me. There is also a file in the repo: https://github.com/coopdevs/timeoverflow/blob/develop/public/favicon.ico

**Comment by sseerrggii** [comment]
Yes, it's only a staging server problem 
I don't know why favicon don't load in staging :thinking:

**Comment by enricostano** [comment]
@markets do you see a favicon in your browser? I don't :thinking:

**Comment by enricostano** [comment]
Probably we should move this issue to https://github.com/coopdevs/timeoverflow-provisioning but I'm still not sure. We need to investigate a bit more.

**Comment by markets** [comment]
@enricostano yep, in production, I can see the favicon in the browser! 

It seems, in staging, all files under `public/` don't respond properly: https://staging.timeoverflow.org/robots.txt .... maybe `nginx` config in staging stage?

Another possibility:   

```
config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
```

We have ☝️ this setting, and probably the gem:

https://github.com/coopdevs/timeoverflow/blob/6d9bbde204118267ea97a6cfb32018a7496e6bfd/Gemfile#L70-L72

makes that true, but only in `production` env. If this is the issue, I'd vote for removing the gem and just configure each env accordingly!

**Comment by enricostano** [comment]
> I'd vote for removing the gem and just configure each env accordingly!

@markets aahhhh "removing"... you know my tastes :joy: :fire: I created a separate issue to investigate that lead: https://github.com/coopdevs/timeoverflow/issues/485
