### ISSUE TITLE
Reactivate "gender" field on User

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#482]
As we discussed on https://community.coopdevs.org/t/reactivar-genero-en-perfil-de-usuario-estadisticas/881/4

We want to reactive gender field on User table. 

We want to add new question on user create/edit form 

**Which gender do you identify with?**

And use a select for te answer: 
* (empty) (by default)
* Women
* Men
* Other
* I prefer not to answer

This question is only for diversity community analysis purposes, so we won't show it in any view. 

We want to add new graph for admins on Statistics -> Demographics data below age graph, same kind of age graph

**Comment by markets** [comment]
@sseerrggii implemented in :point_right: #489
