### ISSUE TITLE
Apply new wireframes

### ISSUE THREAD

**Issue by zarpilla** [coopdevs/timeoverflow#496]
As suggested in https://community.coopdevs.org/t/wireframes-per-mobile-nova-estrategia/933 , the design can be improved using that wireframes.

**Comment by sseerrggii** [comment]
We are waiting @zarpilla small PRs instead of big one #501

Also I suggest to add coopdevs frontend developers as reviewers of this PRs @andresgutgon @mllocs @nadalsol @naoisegolden @Morantron

**Comment by sseerrggii** [comment]
I close that, for the moment we don't have the resources to do it
