### ISSUE TITLE
Add repo topic for "timebank"

### ISSUE THREAD

**Issue by patcon** [coopdevs/timeoverflow#497]
Hiya :)

Seems that the `timebank` topic is related and useful. Worth adding so people can stumble on this repo more easily?

https://github.com/topics/timebank

**Comment by sseerrggii** [comment]
Yes! thank you @patcon I don't known how to do it? Can you do it?

**Comment by enricostano** [comment]
Done, thanks @patcon !

**Comment by patcon** [comment]
No problemo!

Also, the `probot/settings` plugin can be added the repo, which allows changes to repo config (incl topics and descriptions and even names) to be encompassed within the PR workflow. Happy to submit a PR to add minimal config (and a rationalization for consideration) if you're open to it in principle.

https://github.com/probot/settings

**Comment by enricostano** [comment]
I don't think in our case would help us much, we generally don't touch that information. But thanks in any case for letting us know that it can be done, I didn't know that!
