### ISSUE TITLE
Mejoras listados

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#5]
* En usuarios ordenados por categoria, al hacer click sobre código de miembro ir a ver ficha del miembro
* En usuarios ordenados por categoria, hacer el arbol con tabulaciones y los padres con títulos más grandes según jerarquía,
* Que se pueda buscar en usuarios ordenados por categoria 
* En el listado de usuarios mostrar en una columna el campo "otro teléfono"
* Hacer boton con un listado de emails de todos los miembros separados por comas (para luego poder mandar mails a todos los miembros, en la misma sección users)
* Mejorar visionado de un usuario.

**Comment by markets** [comment]
@coopdevs/timeoverflow-contributors I think we can close it. We are discussing this topic in Redbooth.
