### ISSUE TITLE
Edit en.yml donate link in mails

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#504]
As commented on https://community.coopdevs.org/t/el-texto-al-pie-de-los-correos-sobre-el-euro-de-patreon/951/4

I edited https://app.localeapp.com/projects/10031/translations/5898761 waiting for user feedback, if nobody complains about that I'm going to change en.yml to homogenize it with Spanish and Catalan

**Comment by enricostano** [comment]
:+1:
