### ISSUE TITLE
undefined method `updated_at' Exception after a succesfull login

### ISSUE THREAD

**Issue by zarpilla** [coopdevs/timeoverflow#505]
Hi, 

In a fresh installation of timeoverflow, an exception occurred after a valid login:

```
NoMethodError in UsersController#index
undefined method `updated_at' for nil:NilClass
```

app/controllers/application_controller.rb:54:in `check_for_terms_acceptance!'`

![image](https://user-images.githubusercontent.com/3697530/59878043-97604100-93a7-11e9-8577-3e7bd27db594.png)

Commenting the code lines from the exception, member page after login is loaded and all seems ok.

**Comment by enricostano** [comment]
Has seed data been loaded correctly?

**Comment by sauloperez** [comment]
any change @zarpilla ?
