### ISSUE TITLE
organization filter is lost when filtering

### ISSUE THREAD

**Issue by zarpilla** [coopdevs/timeoverflow#508]
In the public url for offers & inquires, i.e: 
https://www.timeoverflow.org/inquiries?org=266
If we make a search, the org parameter is lost, showing the inquires of the other time banks: https://www.timeoverflow.org/inquiries?q=x

**Comment by enricostano** [comment]
Thanks @zarpilla ! I think we had this bug tracked down somewhere, right @sseerrggii?

IIRC this will be solved once https://github.com/coopdevs/timeoverflow/pull/250 will get some love.

**Comment by sseerrggii** [comment]
It's ok to have this issu, thanks @zarpilla :wink: 

We talked about that in https://github.com/coopdevs/timeoverflow/pull/465#issuecomment-466409323 but we didn't create a issue
