### ISSUE TITLE
Add "Search" text placeholder on members view search input

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#509]
I noticed empty placeholder in Search box on /members view

![FireShot Capture 315 - Banc del Temps de Gràcia - staging timeoverflow org](https://user-images.githubusercontent.com/2297137/65233735-9c7e7a80-dad3-11e9-8ada-fdbb9bd27818.png)

We want to add "Search" text like we have it on /offers or /inquiries

![FireShot Capture 314 - Banc del Temps de Gràcia - staging timeoverflow org](https://user-images.githubusercontent.com/2297137/65233688-87095080-dad3-11e9-9909-7ffdc168659a.png)

**Comment by zarpilla** [comment]
Hi Sergi, 

Done in the following [commmit](https://github.com/zarpilla/timeoverflow/commit/65d85742bb56c4f57786139079d255420fe6d101) 

Thanks!

**Comment by sseerrggii** [comment]
Fixed on #501
