### ISSUE TITLE
FOSS application in FOSS repository

### ISSUE THREAD

**Issue by narcisgarcia** [coopdevs/timeoverflow#518]
f-droid.org is a non-profit volunteer project to maintain an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. F-Droid respects user's privacy and people does not need an account to use any interface.
F-Droid catalogue takes care of reporting any antifeature from available software before installing applications, and catalogue itself can be filtered to avoid any trackers.

My feature request is to propose TimeOverflow to be included in F-Droid catalogue, and this way become it more trusted by ICT community and people.

**Comment by sseerrggii** [comment]
Welcome @narcisgarcia 
Have TimeOverflow app for F-Droid will be awesome. 
We used Expo.io to build the iOS & Android app https://github.com/coopdevs/timeoverflow-mobile-app do you know how can we easily build our app for F-Droid?

**Comment by narcisgarcia** [comment]
F-Droid inclusion how-to:
https://f-droid.org/en/docs/Inclusion_How-To/

**Comment by narcisgarcia** [comment]
You can build Android version same way, but adding some ethical review to application and package internals. When you reach privacy and security levels required by F-Droid, you can keep them anyway on other publishing channels.

F-Droid.org is an apps repository that many people trust, because applications published there have been checked already, and people can get them from F-Droid without having to inspect and track one-by-one and without assuming that "there is nothing to do to protect own privacy".

**Comment by sseerrggii** [comment]
Thanks @narcisgarcia ! 

@raneq maybe one day you can help us with that? I will open a issue on  https://github.com/coopdevs/timeoverflow-mobile-app

**Comment by narcisgarcia** [comment]
I'm recommending (and installing) software for many devices. And some times (like now) I can't open and follow more tickets on projects communities.

A new ticket needs to be created at the F-Droid Submission Queue on GitLab ("Proposal by Submission Queue") https://f-droid.org/en/docs/Inclusion_How-To/
