### ISSUE TITLE
Some views in /stadistics are broken in mobile

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#540]
We want to fix some views for admin purposes that are broken in mobile screens, we don't want ti improve UX for admins we only need some responsive, for example /stadistics/statistics_all_transfers show

![Screenshot](https://user-images.githubusercontent.com/2297137/74336410-7d43fa80-4d9e-11ea-88e4-e6b1c5a3a987.jpg)

**Comment by mperezv** [comment]
We can try with .table-responsive, which is going to bring a horizontal scroll inside the container, or by wrapping the content so it goes under the previous content. What do you think is better?
