### ISSUE TITLE
Remove Elasticsearch

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#551]
Back to PostgreSQL full text search again (~> revert https://github.com/coopdevs/timeoverflow/commit/096fcce484ffd4f843955bcc2cd36627e26e43bc).

No memcached, no server crons, no Elastic, no Angular ... such a world, only Ruby, PostgreSQL and Redis 👌 🔝 

@enricostano @sauloperez just adding an issue to track the status of this.

**Comment by sauloperez** [comment]
YES! this is the point where we want to get to!

**Comment by markets** [comment]
Nice!! I'd like to finalize the Rails 6 upgrade (#516) after that. I think it's better to avoid testing the Elastic thing again in Rails 6 and we can save the related Elastic gems upgrade as well (they need to jump like ~3 major versions).

**Comment by sauloperez** [comment]
> Do you have any estimated time for this to happen? :)

Unfortunately not but I'll do my best to plan for it. We're at almost full capacity at Coopdevs these days.

**Comment by markets** [comment]
ok Pau, let me know if I can do anything to help move this forward 👍

**Comment by sauloperez** [comment]
Thanks for the offer! I'll let you know. I plan to sit with @sseerrggii next week and come up with a plan for all the things that in play now :ok_hand:

**Comment by sauloperez** [comment]
Alright, so we did of planning of the upcoming things for TO and we decided to split this into at least two steps. We aim to minimize the risks to the bare minimum and do steps that require very little from @sseerrggii, myself or others in the team. We suggest we start with:

**Comment by markets** [comment]
ok @sauloperez 👍 just a question, in the past we already test that project, why not just revert the revert -> test only 1 time -> merge -> deploy? I think this path requires very little from all of us (ok, I'm not sure about the deploy step 😸, but at the end, it's a migration that will be tested in staging first).

**Comment by sauloperez** [comment]
the only goal was the minimize any problems that may arise in production. We're normally busy and can't afford to put too much attention here. Starting with the structure.sql moves us a little closer and doesn't seem that daunting as doing it altogether would. As a consequence, I might be able to squeeze it in my agenda for the upcoming days. I guess it's just a matter of confidence.

**Comment by sseerrggii** [comment]
Dale caña @sauloperez :muscle: 

When you have a moment, I can test it and :boom:
