### ISSUE TITLE
Error in ansible-playbook playbooks/provision.yml --limit=dev

### ISSUE THREAD

**Issue by oscarmh** [coopdevs/timeoverflow#561]
Hi after running all steps I reached an error running provision.yml

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/timeoverflow-provisioning/roles/database/tasks/main.yml': line 30, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Add hba entry for user
  ^ here

ANy help will be appreciated.

**Comment by sseerrggii** [comment]
Hi Oscar! 
@danypr92 what do yo think?

**Comment by danypr92** [comment]
Hi @oscarmh it's the first time I see this error in this task... :thinking: 

Which environment are you provision? 
Have you set the `database_user`?
Can you see the `pg_hba.conf` config file? (absolute path: `/etc/postgresql/9.4/main/pg_hba.conf`)

**Comment by oscarmh** [comment]
Hi 

ansible 2.5.1
  config file = /root/timeoverflow-provisioning/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
root@bof:~/timeoverflow-provisioning# 


I´m trying to ansible-playbook playbooks/provision.yml --limit=dev --ask-vault-pass

FIle pg_hba.conf is 

 TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

**Comment by danypr92** [comment]
Hi @oscarmh!

Thanks for the information.

We are using Ansible 2.8.2 as you can see in the [`requirements.txt` file](https://github.com/coopdevs/timeoverflow-provisioning/blob/ac5f76972cedc2367eea7a252256554202df847f/requirements.txt#L1).

We recommend you to use the supported version. You can use Python to install it as we do with the `requirement.txt` file.

Can do you update the Ansible package and retry the provisioning process?

**Comment by oscarmh** [comment]
shame for me, retry and let you know, thanks

**Comment by markets** [comment]
@oscarmh I'm going to close this one, please re-open in case you still got issues after @danypr92's comment. Thanks
