### ISSUE TITLE
"Improve the export of reports"

### ISSUE THREAD

**Issue by dataf3l** [coopdevs/timeoverflow#569]
how can one download offers in json or xml or rss format?

https://www.timeoverflow.org/offers/

is there a url for that?

**Comment by sseerrggii** [comment]
Hi @dataf3l 

TimeOverflow don't have this feature. We want to develop the hability to export data https://github.com/coopdevs/timeoverflow/pull/259 but for now we don't have resources to develop that

**Comment by dataf3l** [comment]
What about CSV export of all the fields, or maybe XLSX export, would that be easier?

**Comment by sseerrggii** [comment]
Yes, would be easy for common users @dataf3l but we actually don't have this feature request...

Anyway if you want to develope it, I think this will be a good feature for TimeOverflow admin users :+1:

**Comment by dataf3l** [comment]
I might develop it.
please re-open and assign it to me.
I'll spend some time this weekend on it.

**Comment by sseerrggii** [comment]
Yes, i only closed it because I thought it was just a question

**Comment by sseerrggii** [comment]
Can yo edit de title @dataf3l  something like "Improve the export of reports"

**Comment by sseerrggii** [comment]
Added on https://github.com/coopdevs/timeoverflow/pull/581

**Comment by dataf3l** [comment]
this is awesome. can you please explain how I can now perform the "CSV export of all the fields, or maybe XLSX export" in the user interface?

**Comment by sseerrggii** [comment]
Hi @dataf3l for the moment this feature is for admin users

As admin of a organization you will see the reports on the navbar

![Screenshot_2021-01-11 Banc del Temps de Gràcia](https://user-images.githubusercontent.com/2297137/104161298-edb22c00-53f2-11eb-8eee-32e0935b2f0d.png)
