### ISSUE TITLE
Search on old posts

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#583]
We have a problem until we  remove Elastic Search https://github.com/coopdevs/timeoverflow/pull/568

The Post search only find new posts. 

For exemple if you search (logged out) for "pagina"  https://www.timeoverflow.org/offers?q=pagina

You will find one post from december of 2020 https://www.timeoverflow.org/offers/29150 

but you have older post with "pagina" in text like https://www.timeoverflow.org/offers/769 

@sauloperez suggest to update our database in order to update database indexes

**Comment by markets** [comment]
@sseerrggii @sauloperez As per https://github.com/Casecommons/pg_search/wiki/Building-indexes, we can try running the following command in console: `ActiveRecord::Base.connection.execute("UPDATE posts SET id = id")` to avoid touching the updated_at attribute, in case that command didn't work, we can run: `Post.find_each(&:touch)` (**DOWNSIDE** all posts will update the updated_at attribute)

**Comment by sseerrggii** [comment]
It works @markets 

I tried in staging first and works so I executed to production too. Also the execution was really quick. 

Thanks @markets and @sauloperez
