### ISSUE TITLE
Feature: onboarding phase one

### ISSUE THREAD

**Issue by franpb14** [coopdevs/timeoverflow#621]
I am opening this Issue to implement a new functionality for those who are looking for a organisation. I've defined this Issue with the help of @sseerrggii, the first phase will be a listing with a searcher as you can see in the following mockups. 
<img width="715" alt="First" src="https://user-images.githubusercontent.com/70280187/115524486-7bbd6e80-a28e-11eb-8f44-7e8e07b5f8b6.png">
<img width="714" alt="Second" src="https://user-images.githubusercontent.com/70280187/115526496-62b5bd00-a290-11eb-8301-dd5ab7271711.png">

After clicking the user will see the organisation's information with a message to encourage the user to contact the organisation. 

The second phase could be to incorporate a map in addition to the list. The map could have both timeoverflow organisations and others.

**Comment by markets** [comment]
like the feature! I think we should add this "search" in this page: https://www.timeoverflow.org/organizations
