### ISSUE TITLE
Feature: search members by post code or tags

### ISSUE THREAD

**Issue by franpb14** [coopdevs/timeoverflow#623]
This feature is about being able to search for members of an organisation by postcode or tag (each organisation may choose its own tag policy or not use tags directly). With the postcode, large organisations can put their closest members in touch with each other.

Main points:

- [x]  Add tags (optional text) and postcode (optional string) fields and add them to the forms.
- [x] Make the current searcher work on the postcode and a dropdown with tags. (At the end you can see a mockup of this).
- [x] Autocomplete tags in forms.

The mockup:
![MocupsBuscarUser](https://user-images.githubusercontent.com/70280187/115856066-49497800-a42c-11eb-8c01-7243696a46df.png)

**Comment by sseerrggii** [comment]
Thanks @franpb14 

I think we don't need search for postal code, we only want to create this field for users because someday we want to develop features based on geolocalization of users

**Comment by franpb14** [comment]
@markets the changes made to the "structure.sql" [on this commit](https://github.com/coopdevs/timeoverflow/commit/59ae149956d57accd6a556affa427438e3d2240c#diff-1dd5a8f580b9615769ddc19a64a98f455d9d20eb149c443f41d9d3c797d39b12) are causing Travis to fail again as before  (and in the same two tests). But now the `bin/rails migrate` is necessary. I've thought about changing the "structure.sql" by adding the rows in the tables and don't run the migrate, but I don't think it's a good idea.

**Comment by markets** [comment]
Maybe you are using a different postgresql version? We are at 9.4:

- **INFRA**
https://github.com/coopdevs/timeoverflow-provisioning/blob/7d848fc6dd060d3fcecb824440941891cd235089/roles/database/tasks/main.yml#L10

- **CI**
https://github.com/coopdevs/timeoverflow/blob/6da895d1a8eba818b3a836031c80923d15785c8f/.travis.yml#L7

In the meantime, maybe we can edit manually the "structure.sql" to restore all unnecessary changes (we only need to reflect the new columns and the migration version), but of course this is not a long term solution :(

**Comment by franpb14** [comment]
Yeah, it was the version of postgres, thanks for your help @markets.
