### ISSUE TITLE
Feature: profile photo for users

### ISSUE THREAD

**Issue by franpb14** [coopdevs/timeoverflow#627]
The idea is that the current "change your image" button will not be a link to gravatar but the user will be able to choose a photo from his computer. This photo will be stored in a backblaze bucket. 

I will not break the integration with gravatar as the default gravatar photo will continue to be used until the user changes it.

**Comment by markets** [comment]
Are we sure about the storage provider? Ideally we should use [ActiveStorage](https://edgeguides.rubyonrails.org/active_storage_overview.html#setup) and it seems they don't have native support for this provider.

**Comment by sseerrggii** [comment]
Hey! We don't have a decision about backblaze, it's a provider we use at coopdevs to avoid Amazon

@markets do you have other options?

**Comment by markets** [comment]
I usually go with AWS S3, but ActiveStorage have also native support for Google Cloud and Microsoft Azure. 

I've found a gem for `backblaze` integration: https://github.com/jeygeethan/activestorage-backblaze. But not sure how stable/up-to-date this repo is... In terms of support and maintenance, I'd go with S3.

**Comment by sseerrggii** [comment]
So, let's do it with AWS, I will create an account for ADBdT/TimeOverflow and grant you access

**Comment by markets** [comment]
Thanks @sseerrggii! The AWS key will be needed for staging/production, for development we can use the local filesystem adapter. So, we don't need that key to move forward with the code changes.
