### ISSUE TITLE
Limit profile image size to 5MB

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#644]
I have noticed that when you exceed the maximum file size when changing profile image, nginx gives an error "413 Request Entity Too Large"

It would be better don't allow uploading files greater than 5MB to avoid this error appearing 

![Screenshot 2021-06-15 at 17-04-49 413 Request Entity Too Large](https://user-images.githubusercontent.com/2297137/122077364-f7094f80-cdfb-11eb-9ecb-d63327f5fc6d.png)

**Comment by markets** [comment]
100% agree! Probably, some js validations will be enough for now 💅🏼
