### ISSUE TITLE
Migrate from TravisCI to GitHub Actions

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#646]
TravisCI worked really well for years, but after all changes they made in latest times, also for OSS projects... time to say 👋🏼 

GH Actions are really cool and flexible ✨ 

Some interesting articles about Travis:
 - https://daniel.haxx.se/blog/2021/06/14/bye-bye-travis-ci/
 - https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
 
 Things to be considered:
 - We need Postgresql 9.4
 - We'd like to keep CodeClimate Test Coverage reporting
 
Help much appreciated! 🤝

**Comment by sauloperez** [comment]
Definitely, OFN started this migration recently as well. We can copy its configuration :point_right: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/.github/workflows/build.yml, although Github's guides are pretty complete and we shouldn't have any problem.

> We need Postgresql 9.4

That looks reaaaally old :see_no_evil: We should probably plan an upgrade.

**Comment by markets** [comment]
@sauloperez couple of comments:

1) about the CodeClimate thing, I just see there is also an official GH Action app for CodeClimate in the marketplace, so we can keep both report: Quality and Coverage (not sure if CodeCov reports also Quality). So, I'd stick with CodeClimate for now.

2) About Postgresql version, 100% agree, we should plan an upgrade sooner than later, but I'd do it separately from this migration. This will need some coordination with Infra and probably a rebuilt of the `structure.sql` file in the repo.
