### ISSUE TITLE
[Idea: major UX change] Non-zero-sum transactions

### ISSUE THREAD

**Issue by jwmh** [coopdevs/timeoverflow#655]
Hi y'all,

I just searched github for "timebank" and found this repo! 
♥
My local community doesn't have any app (am hoping for an android apk eventually).

Here is a radical proposal:

To prototype a non-zero-sum economic model.

Rather than a single "balance",
Instead,
Superadmins could add or modify a transaction type to be "non-zero-sum":
... such that Users would then have TWO (2) separate, infinite tally scores: 
(A). Hour Given;  or
(B). Hour Received.

That way,
 Person's "credit score" (if desired) could be calculated as either the difference (subtraction), or the quotient (division / ratio), of their two tallies.

Multiple radical economic systems have long since been proposed with this general idea in mind.

Obviously, lots more to say here and potentially discuss (I would reference other models and papers on economic theory).... I wanted to drop this here as a potential starting pont for discussion, to gauge potential interest.

The basic idea is that time, as such, doesn't and need not represent any actual scarcity (which is what zerosum economics is all about).  Zerosum economics use transferrable currencies (e.g. the dollar, bitcoin, timehours) as an assumption of scarcity of value.
However, in today's society w 8,000,000,000 of us, and 40% of food (and any other massproduced commodity) going to waste, it does seem (to me and others) a little preposterous that we are still transacting inside of an economic framework built on an assumption of scarcity of wealth/resources.

On the contrary, we now exist within an *artificial* scarcity, where (e.g. when the City of Detroit declared bankruptcy around a decade ago),
there was in point of fact ZERO actual scarcity -- neither of housing, nor of food/water/other commodities, nor of important/useful work to be DONE, nor of available WORKERS (humanhours) to do the work...!
In fact the *only* thing lacking was...   
... Capital (or rather, means of /access/ to capital).

So.
Hence this issue being opened ;-)

Dialogue (and criticism) very, very welcomed.
Am happy to point to papers or research on existing economic work (and, no, I am not referring to MMT here, which still rests on the dollar or similar zerosum representation of capital, altho i think their heart is coming from a good place).

P.S. edit
Just realised I ought to add:
Obv there are both IRL & UX challenges as well as technology hurdles to overcome here.
1. Irl, e.g. what is to stop users gaming such a system or committing fraud (creating a timebank fraud ring, if you will, saying they each did so many hours' work for each other, when in fact not).
2. Technology:  well obv this would become a huge fundamental shift in both the software and support for it.

So lots of challenges for sure!
I am not oblivious to these, just that I feel it would be immensely worthwhile in the long run! The net benefit to communities could be huge.  And, maybe, to research as well... Can be used for Sociology studies e.g. "Beyond the Tragedy of the Commons" (an excellent paper worth reading even the abstract summary).

**Comment by sseerrggii** [comment]
Hi @jwmh and welcome 

Thanks for your proposals. We always think on methods to facilitate interactions in a timebank community trough TimeOverflow :) Our main problem right now are resources to develop consistently our app... Nowadays we do really small changes to the app

Other platforms (enterprise owned) like https://timerepublik.com/ have more capability to implement frequent changes... 

For that reason we are in conversations to work together with other projects like CES, IntegralCES, Community Forge, ... in order to find a formula that provide us a better way to empower mutual credit communities trough technology
