### ISSUE TITLE
Show icon on Post categories

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#673]
We want to show icons from [glyphicons](https://getbootstrap.com/docs/3.3/components/#glyphicons) to identify post categories, the icons are: 

Acompañamiento
glyphicon glyphicon-random

Asesoramiento
glyphicon glyphicon-briefcase

Clases
glyphicon glyphicon-education

Estética
glyphicon glyphicon-scissors

Ocio
glyphicon glyphicon-music

Otros
glyphicon glyphicon-asterisk

Préstamo de herramientas, material, libros, ...
glyphicon glyphicon-wrench

Salud
glyphicon glyphicon-apple

Tareas administrativas
glyphicon glyphicon-list-alt

Tareas domésticas
glyphicon glyphicon-shopping-cart

Te places to add it are before the name of category on: 

* Post list
![Banc-del-Temps-de-Gràcia (3)](https://user-images.githubusercontent.com/2297137/212498298-770afea5-70d3-4997-a3f5-b317be2a18e5.png)
* Post detail
![Banc-del-Temps-de-Gràcia (4)](https://user-images.githubusercontent.com/2297137/212498304-fb370c80-b701-4b0d-91f8-bc15f2dbf8b0.png)
* Post search modal
![Captura de pantalla_2023-01-14_22-41-22](https://user-images.githubusercontent.com/2297137/212498341-26902ea0-8714-4391-8c7b-7d0f5033abf5.png)

**Comment by markets** [comment]
@sseerrggii implemented in #663:

![Captura de pantalla 2023-02-03 a las 1 07 26](https://user-images.githubusercontent.com/576701/216479550-3f164331-5331-4b79-ad75-debed8eb83fd.png)

**NOTE** Since categories are editable, I added a fallback to the current icon 📁 in case the name is not found.

**Comment by sseerrggii** [comment]
Thanks @markets !! awesome :heart_eyes: 

We need to wait a little longer for the DevOps work to be able to deploy :S
