### ISSUE TITLE
Add 'active/deactivated' status into 'Users' report

### ISSUE THREAD

**Issue by JohnGillanders** [coopdevs/timeoverflow#689]
In Reports -> Users, it's not possible to tell which users are deactivated.
Please add a column showing the status of the user (in English, I would suggest the labels to use should be "Active" and "Deactivated").

**Comment by markets** [comment]
Hi @JohnGillanders 👋🏼 Actually it renders only "Active" members.

**Comment by JohnGillanders** [comment]
@markets - oops, thank you for clarifying that. I will close this issue, then!
