### ISSUE TITLE
Visitors have difficulty finding how to join the timebank

### ISSUE THREAD

**Issue by nflorentin** [coopdevs/timeoverflow#715]
Hi,

Our first newcomers had difficulty to find the button to make a petition to join the timebank.

I think the problem is that on mobile, the button is not visible on the screen unless you scroll to the right.

Also, I think that it is a bit counterintuitive that this button is only present on organizations list and not on the organization show page. It makes harder to simply share the link of the organization show page to a person.

My proposal:
- add the button on the show page

As a side fix, I also propose to only show "update" button of organization show page if the user has the permission to do it (instead of letting him click and have an error message)

Some screenshots to ilustrate:
![Capture d’écran 2023-12-05 à 08 06 56](https://github.com/coopdevs/timeoverflow/assets/5750349/807680ff-233f-4ceb-8104-ebe3e5df3f2c)
![Capture d’écran 2023-12-05 à 08 05 21](https://github.com/coopdevs/timeoverflow/assets/5750349/edffeaf8-a9fc-41cd-b8f7-02878986fff8)

Let me know what do you think :-)

Have a nice day

**Comment by markets** [comment]
Hi @nflorentin 👋🏼 

100% agree with both changes! Feel free to send a pull request.
