### ISSUE TITLE
alguien puso un height de 178 px en los cards y ahora los cards se renderizan pobremente

### ISSUE THREAD

**Issue by dataf3l** [coopdevs/timeoverflow#729]
hay forma de usar min-height en vez de height?
hay forma de hacer que todos los cards aparezcan del mismo tamaño a pesar de que estos contengan contenidos diferentes?
qué debe hacer el sistema cuando el tag abajo del nombre sea demasiado largo?
hay forma de poder leer el texto sin truncarlo?

son preguntas que tengo, gracias de antemano por su valioso tiempo y colaboración con esta sugerencia.

**Comment by dataf3l** [comment]
Hola. hasta donde entiendo la propiedad "height" funciona igual en todos los navegadores. entonces creo que el problema es el dataset de prueba que no incluye datos que sean diseñados para deformar la interfaz, como cadenas largas, largos valores en ciertos campos, etc.


<img width="1440" alt="Screenshot 2024-01-16 at 05 28 36" src="https://github.com/coopdevs/timeoverflow/assets/3528304/6640f6cf-1ab9-477a-bf13-c456bcea5cc2">

**Comment by sseerrggii** [comment]
Hola @dataf3l disculpa que ya no te dije nada más, estamos liados con cambios de infra https://github.com/coopdevs/timeoverflow/pull/722 y no llegamos a todo

Te animas a proponer una Pull Request que solucione esto?

**Comment by gmartincor** [comment]
Hola! Estaría interesado en poder participar en el proyecto e intentar resolver este issue :smiley: .

Muchas gracias.

**Comment by sseerrggii** [comment]
Hola Guillermo! Genial, hace tiempo que está por aquí :) Realmente hay bastante cosa que se podría mejorar de UI/UX

Para hacer propuestas de mejora solo tienes que abrir una Pull Request, lo revisamos y lo testeamos

**Comment by gmartincor** [comment]
Hola Sergi! 

Un placer poder colaborar y participar en el proyecto.

**Comment by dorremifasol** [comment]
Buenas tardes:

Desde nuestro BdT en Girona proponemos cambiar el icono del reloj en la versión móvil de TimeOverflow que sirve para hacer transferencias de tiempo.  Algunos usuarios no entienden este dibujito,  si se pudiera agregar  una explicación como "transferir tiempo", "registrar intercambio"o  algo así, sería más claro.

Por otro lado, se  nos acumulan las solicitudes duplicadas, la última  aparece hasta 14 veces, cuando ya ha sido aceptada.  Esto está dificultando las tareas de los administradores, ya se por edad, dificultad visual, etc.

**Comment by sseerrggii** [comment]
Hola @dorremifasol ! Bienvenida!! 

Tú comentario no está relacionado con esta issue, son dos issues separadas de dos mejoras, cuando pueda las creo por separado
