### ISSUE TITLE
Fix links to community

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#734]
@sseerrggii it seems that https://community.coopdevs.org is down 🤔? In that case we should think something to replace a couple of mentions: https://github.com/search?q=repo%3Acoopdevs%2Ftimeoverflow%20community.coopdevs.org&type=code, assuming we don't want the Discourse back.

**Comment by sseerrggii** [comment]
Yes, I will fixed :)
We won't have Discourse back
