### ISSUE TITLE
New categories for offers/requests

### ISSUE THREAD

**Issue by JohnGillanders** [coopdevs/timeoverflow#739]
The New Zealand timebanks on TimeOverflow have come together to request adding the following categories (new entries added to those on the drop-down list which appears when creating/editing an offer or request/inquiry):

Arts / Crafts / Music
Garden
Transport
Food / Drink
Animal care
Caregiving
Child Care
Community Activities
Repair / Mend
Tech help
Help our Organisation

**Comment by markets** [comment]
Hi @JohnGillanders 

Let me share the current list, so we can see if there is any overlap:

<img width="273" alt="Captura de pantalla 2024-04-16 a las 19 29 41" src="https://github.com/coopdevs/timeoverflow/assets/576701/09796372-3ea3-458b-a74c-902ed66380bd">

@sseerrggii What do you think? Should we add all of them or you have want only some of them?

**Comment by JohnGillanders** [comment]
Hi Marc & Sergi,Thanks for looking at this. The NZ TimeBanks came up with this list as being common categories of offers/requests/exchanges that were not covered by the current list, so there should not be any significant overlap. These represent things that happen often.They would greatly appreciate it if all could be added rather than only some.Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 17/04/2024, at 5:31 AM, Marc Anguera ***@***.***> wrote:﻿
Hi @JohnGillanders
Let me share the current list, so we can see if there is any overlap:
Captura.de.pantalla.2024-04-16.a.las.19.29.41.png (view on web)
@sseerrggii What do you think? Should we add all of them or you have want only some of them?

**Comment by markets** [comment]
Ok @JohnGillanders 👍🏼 Will discuss it with @sseerrggii, probably there is no overlap, but maybe that's too much "main categories"? The list will grow more than x2, so this dropdown will be quite big. Don't forget we also have the Tags concept, they are really useful for refining and adding any label.

**Comment by JohnGillanders** [comment]
Hi Marc,Thanks. Yes, they could use tags, but felt that the additional categories are all useful and common (e.g. they were very surprised that gardening, one of the most common Timebank exchanges was not on the list but other much less used categories in NZ were on the list).Might be good to know stats of how often categories are used to see if any of the current categories are hardly used…?I I take your point that the list would get much larger, but still it seems within reason to us. Thanks for discussing it with Sergi.Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 17/04/2024, at 9:44 AM, Marc Anguera ***@***.***> wrote:﻿
Ok @JohnGillanders 👍🏼 Will discuss it with @sseerrggii, probably there is no overlap, but maybe that's too much "main categories"? The list will grow more than x2, so this dropdown will be quite big. Don't forget we also have the Tags concept, they are really useful for refining and adding any label.

**Comment by JohnGillanders** [comment]
@sseerrggii / @markets:
The following are translations into Spanish of the new categories, provided by Tai Tokerau Timebank. They told me that these were translated by a local native Spanish speaker and his wife who is a native English speaker so nothing should have got lost in translation.

Manualidades / música
Jardinería
Transporte
Comida / bebidas
Cuidado animales
Cuidado de otras personas
Cuidado de niños
Actividades comunales
Reparaciones
Ayuda tecnológica
Ayuda en nuestra organización

(English:)
Arts / Crafts / Music
Garden
Transport
Food / Drink
Animal care
Caregiving
Child Care
Community Activities
Repair / Mend
Tech help
Help our Organisation

**Comment by sseerrggii** [comment]
Hi @JohnGillanders sorry for the slow tempos, we will work on it on ADBdT.org association and response here

**Comment by JohnGillanders** [comment]
Thank you, Sergi.Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 13/06/2024, at 8:41 PM, Sergi Alonso ***@***.***> wrote:﻿
Hi @JohnGillanders sorry for the slow tempos, we will work on it on ADBdT.org association and response here

**Comment by sseerrggii** [comment]
Hi  @JohnGillanders here is proposal from ADBdt.org
![WhatsApp Image 2024-06-19 at 20 57 02](https://github.com/coopdevs/timeoverflow/assets/2297137/c390da71-75a7-4dac-8fc4-935ab58218e7)
What do you think?

**Comment by JohnGillanders** [comment]
Hi Sergi,

Thank you.

I have emailed to the New Zealand timebanks that use TimeOverflow and will let you know their feedback.

My own opinions (not representing any timebanks actively using TimeOVerflow, though) are:
That the ‘Garden’ category is missing and is one of the most popular categories, and so can that please be added as its own category?
I can see how “Community Activities” and “Help our Organisation” are very similar and so I understand why ‘Help our Organisation’ has been left off.
I am not really in favour generally of grouping together the categories as it makes it less easy to accurately report on activities. I believe that the list we came up with was not actually a very long list overall so feel that it would be better to keep them as separate categories, but I think that ADBdT are concerned about it being too long a list. Ultimately, the proposal is still a significant improvement compared to what’s in there now if ADBdT go ahead with the new list with some of the categories grouped together.
I see Companionship and Caregiving as being fairly different. Companionship is mostly social whereas Caregiving implies helping take care of basic needs. I think these should be separate.
Cooking under ‘Help at home’ isn't needed since that would go under ‘Food / Drink’ (which would cover cooking, fermenting, smoothies, juice-making, raw recipes etc.)
Then if ‘Cooking’ is removed from that category, it seems unnecessary to specifically including only Cleaning only as part of Help at Home but no other sub-categories, so I’d prefer it to just stay ‘Help at home’ in that case.

Let me know if you have any questions on my feedback, and I’ll let you know once I hear from the other timebanks.

Ngā mihi,
John Gillanders
Managing Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology
027 486 1533

**Comment by JohnGillanders** [comment]
Hi Sergi,

I have agreement from both timebanks who have responded that they agree with my comments.

In addition, one of the timebanks said this, which I agree with:


Companionship is totally different to caregiving. If we need to combine two, perhaps child care and caregiving could be under the one 'caregiving' 

So, looking at the last section of the last column on the pic you linked to, 'new structure', the 'rename' section should just be:
Admin and Tech
Companionship
Help at Home
Leisure/ Arts/ Crafts/ Music

And I'd suggest renaming Child Care to Caregiving (to encompass care for any age/ situation).

Regards,
John Gillanders
Managing Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology
027 486 1533

**Comment by sseerrggii** [comment]
Hi @JohnGillanders How about this proposal from ADBdT?

![WhatsApp Image 2024-07-01 at 20 12 11](https://github.com/coopdevs/timeoverflow/assets/2297137/046a83d1-1a9d-4604-8d9f-321e2ad8262d)

**Comment by JohnGillanders** [comment]
Hi Sergi,Looks good to me, and I already had a few of the TimeBanks here saying they agreed with my previous comments so I think they will agree to this.I’ll forward to the TimeBanks and let you know their feedback.Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 11 Jul 2024, at 7:18 PM, Sergi Alonso ***@***.***> wrote:﻿
Hi @JohnGillanders How about this proposal from ADBdT?
WhatsApp.Image.2024-07-01.at.20.12.11.jpeg (view on web)

**Comment by JohnGillanders** [comment]
Hi again,

So far two of the timebanks have responded and both are happy with this proposal. I’ll let you know when any others respond.

Ngā mihi,
John Gillanders
Managing Director
Technaturally
www.Technaturally.info <http://www.technaturally.info/>
Your Life, Enriched by Technology
027 486 1533

**Comment by JohnGillanders** [comment]
Please go ahead with the proposed changes. I heard from a third timebank and all three agree to this proposal.Thank you!Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 13 Jul 2024, at 8:00 AM, John Gillanders ***@***.***> wrote:﻿Hi again,So far two of the timebanks have responded and both are happy with this proposal. I’ll let you know when any others respond.
Ngā mihi,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533

On 11/07/2024, at 8:01 PM, ***@***.*** ***@***.***> wrote:Hi Sergi,Looks good to me, and I already had a few of the TimeBanks here saying they agreed with my previous comments so I think they will agree to this.I’ll forward to the TimeBanks and let you know their feedback.Regards,John GillandersManaging DirectorTechnaturallywww.Technaturally.infoYour Life, Enriched by Technology027 486 1533On 11 Jul 2024, at 7:18 PM, Sergi Alonso ***@***.***> wrote:﻿Hi @JohnGillanders How about this proposal from ADBdT?WhatsApp.Image.2024-07-01.at.20.12.11.jpeg (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sseerrggii** [comment]
We have updated the categories!! :tada:  Thanks for your patience :)

**Comment by markets** [comment]
Nice 👏🏼👏🏼

Thanks @sseerrggii! I think it will be nice to have the same set in staging, so they will match production data 👌🏼 

<img width="718" alt="Captura de pantalla 2024-08-07 a las 18 03 43" src="https://github.com/user-attachments/assets/78956e45-40dd-41ce-98a4-cc560ad12548">

**Comment by markets** [comment]
@JohnGillanders feel free to close the issue 🤝

**Comment by JohnGillanders** [comment]
Great, thank you for implementing this!
