### ISSUE TITLE
[CI] Docker build is failing

### ISSUE THREAD

**Issue by markets** [coopdevs/timeoverflow#755]
[This workflow](https://github.com/coopdevs/timeoverflow/blob/develop/.github/workflows/docker_build.yml) started to fail 2 months ago. 

Example of latest run (https://github.com/coopdevs/timeoverflow/actions/runs/10961714051/job/30439278832):

<img width="871" alt="Captura de pantalla 2024-09-20 a las 17 12 03" src="https://github.com/user-attachments/assets/fe6f2fe4-3cf7-484b-bc01-bd835d36ef3c">

@microstudi Could you please 🙏🏼 help me with this one?

**Comment by sfrias** [comment]
Perhaps if you open /home/runner/work/_temp/e...13a3.sh and see real first line, you can evaluate why fails. Best wishes.

**Comment by microstudi** [comment]
I think newer version of docker have compose integrate and it mus be called like thi:
`docker compose up -d`

**Comment by markets** [comment]
Thanks @microstudi 🙌🏼
