### ISSUE TITLE
Transfer time Icon

### ISSUE THREAD

**Issue by dorremifasol** [coopdevs/timeoverflow#762]
Hi everyone,

We are writing from Girona's Timebank.  Many of our members have troubles understanding  part of TimeOverflow app or mobile website, especially when they have to transfer time, because they  don't understand the meaning of the little clock shown on the right side, in the member's profile, which is used for these transactions .  We believe it would be advisable to indicate the meaning  of this icon,  exactly as it can bee sean in the desktop version of TimoeOverlow.   

Thank you!

**Comment by sseerrggii** [comment]
To clarify, I leave the screenshots of how it looks on desktop and mobile, what we need is to show "transfer time" text also on mobile so users can understand it better.

Desktop
![Captura de pantalla de 2024-10-24 09-41-16](https://github.com/user-attachments/assets/16d1cc35-dbc4-40df-ada8-b4220223b318)


Mobile
![Captura de pantalla de 2024-10-24 09-42-54](https://github.com/user-attachments/assets/1e612869-41d3-438f-a903-b7084a74aaa1)

**Comment by gmartincor** [comment]
Hello! @sseerrggii 👋, I’ve thought about this sketch for the design of the mobile version. Do you think it’s a good idea?"

Best Regards!😁


![boceto](https://github.com/user-attachments/assets/8310a0e5-c6c5-4d19-bd8e-56a0876d72ba)

**Comment by sseerrggii** [comment]
Yes, perfect, go ahead :)

**Comment by gmartincor** [comment]
Hello @sseerrggii , I've been considering possible solutions, and I think a quick fix, given that an update to the Bootstrap version will be done, could be to remove the hidden-xs and hidden-sm classes from the HTML element. In this case, the view for mobile phones would look as follows:

![móvil timeoverflow](https://github.com/user-attachments/assets/8a8e1119-678a-4f5f-842e-4df71a6902a8)


Another solution could be to build a flex-box structure within the panel-body container and give the desktop version a design similar to the current one, while the mobile version would follow the mockup layout.

I look forward to your feedback. 😁

**Comment by sseerrggii** [comment]
Thanks @gmartincor for taking a look 😉

I prefer remove the hidden-xs and hidden-sm

**Comment by markets** [comment]
Thank you all! The fix for this one has been merged and it will be live in next release.
