### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by rewritten** [coopdevs/timeoverflow#86]
Get to an agreeent for remaining styles (mainly, line length and hash literla indentation), configure rubocop and make it work.

**Comment by rewritten** [comment]
Para mi esto es ok. La configuración de rubocop actual marca el code style preferido. Concretamente tenemos:
* Max line length: 80
* Hash syntax: one space, no value alignments.

**Comment by rewritten** [comment]
@markets close?

**Comment by markets** [comment]
:+1:
